### ISSUE TITLE
Crash without error

### ISSUE THREAD

**Issue by codecompliant** [Fredolx/open-tv#44]
Thank you for this app. It seems to work great except for it closes after a minute of playback.
Is there a way to access an error log or debug tool?

Windows 11

**Comment by Fredolx** [comment]
Generally that's due to your iptv provider. For the error logs, you must add 
```
--log-file=C:\Users\myuser\Desktop\output.txt"
```
to the global mpv parameters in the app's settings.
The path (C:\Users\myuser\Desktop\output.txt) is an example, pick whatever you like.
If it's due to your IPTV provider you'll see an EOF (end of file) error at the end of the logs.

**Comment by Fredolx** [comment]
Proper error reporting was added to Open TV. Errors that are not shown in the UI are also logged in $XDG_CACHE_HOME
